spring:
  application:
    name: eFarda1

  cache:
    #    cache-names:
    #      - rate-limit-buckets
    #    caffeine:
    #      spec: maximumSize=100000,expireAfterAccess=3600s

    jcache:
      config: classpath:ehcache1.xml

  datasource:
    url: jdbc:mariadb://localhost:3307/amir
    username: root
    password: qwer
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 100
      idle-timeout: 10000
      max-lifetime: 60000

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  jpa:
    hibernate:
      ddl-auto: none

#bucket4j:
#  enabled: true
#  filters:
#    - cache-name: rate-limit-buckets
#      url: /api/v1/area.*
#      strategy: first
#      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
#      rate-limits:
#        - cache-key: "getHeader('X-api-key')"
#          execute-condition: "getHeader('X-api-key').startsWith('PX001-')"
#          bandwidths:
#            - capacity: 100
#              time: 1
#              unit: hours
#        - cache-key: "getHeader('X-api-key')"
#          execute-condition: "getHeader('X-api-key').startsWith('BX001-')"
#          bandwidths:
#            - capacity: 40
#              time: 1
#              unit: hours
#        - cache-key: "getHeader('X-api-key')"
#          bandwidths:
#            - capacity: 20
#              time: 1
#              unit: hours

